import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ModalProvider } from "@/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container h-screen flex flex-col gap-y-4 data-[scroll-locked]:px-16 data-[scroll-locked]:!mx-auto `}
      >
        <ModalProvider />
        {children}
      </body>
    </html>
  );
}
